version: "3.8"

services:
  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      BACKEND_URLS: "http://server1:80,http://server2:80,http://server3:80"
      HEALTH_CHECK_INTERVAL: 30

  server1:
    build:
      context: ./http-server
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      PORT: 80

  server2:
    build:
      context: ./http-server
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    environment:
      PORT: 80

  server3:
    build:
      context: ./http-server
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    environment:
      PORT: 80
